# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind / split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to the tmux.conf you want to use)
bind R source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Custom shortcut to rename pane
bind-key r command-prompt -p "New pane name:" "select-pane -T '%%'"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
#set-option -g allow-rename off

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour green

# copy mode
setw -g mode-style 'fg=white bg=#003388 bold'

# panes
set -g pane-border-style 'fg=#555555'
set -g pane-active-border-style 'fg=#bbcc00'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=black fg=white'

set -g status-left "#{?client_prefix,#[bg=#bb00cc fg=#000000 bold] CMD ,#[bg=#bbcc00 fg=#000000 bold] NORMAL }"
set -g status-left-length 10

set -g status-right-style 'fg=black bg=#bbcc00'
set -g status-right ' %Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=#bbcc00'
setw -g window-status-current-format ' #I #W #F '

# Enable displaying content in the pane borders
set -g pane-border-status top 
# Define what to display in the pane border (e.g., index and title)
set -g pane-border-format " #P: #{pane_title} "

# messages
set -g message-style 'fg=white bg=#660077 bold'




